### ISSUE TITLE
Usage in TypeScript project where `"allowSyntheticDefaultImports": false`

### ISSUE THREAD

**Issue by charlesfries** [ungap/structured-clone#10]
I am trying to get this package working in my TypeScript app that doesn't allow synthetic default imports.

```js
// tsconfig.json
{
  "allowSyntheticDefaultImports": false,
  "esModuleInterop": false,
}
```

I can import `structuredClone` using the asterisk syntax without any warnings:

```js
import * as structuredClone from '@ungap/structured-clone';
```

However when I go to call `structuredClone()` I see a function dne error: `TypeError: structuredClone is not a function`

Logging `structuredClone` yields this object:

```js
{
  default: ƒ,
  deserialize: ƒ,
  serialize: ƒ,
  __esModule: true,
}
```

```js
// package.json
{
  "@types/ungap__structured-clone": "^0.3.0",
  "@ungap/structured-clone": "^1.0.1",
}
```

**Comment by WebReflection** [comment]
If you import `*` from the module you need to use `structuredClone.default(…)` instead

**Comment by charlesfries** [comment]
@WebReflection The type declarations don't support that syntax. Should I make a PR in DefinitelyTyped that supports that kind of invocation? What's the proper way to go about this?

**Comment by WebReflection** [comment]
@charlesfries I'm afraid I don't use TypeScript so I don't know the best way to support it **but**, if you do, please file a PR and I'll push it forward 👍

**Comment by timalanfarrow** [comment]
To future readers, it is possible to do:

```
npm i -s @ungap/structured-clone
```

```
npm i -d @types/ungap__structured-clone
```

Then in your code:

```ts
import structuredClone from '@ungap/structured-clone';
```
