### ISSUE TITLE
Support full clone of Errors

### ISSUE THREAD

**Issue by naz** [ungap/structured-clone#12]
### Problem

Currently there is no way to perform a full copy of an instance that is created from a class that extends `Error`. This is due to limited "message" and "type" properties [being used from a copied error instance](https://github.com/ungap/structured-clone/blob/e95ae4e171c10d81e4bc1cf2f4b09e7dfd2d36c6/esm/serialize.js#L139-L140). This results in partial clone of the instance.

### Example

If we have a class extending an error with additional properties like so:
```js
class SpecialError extends Error {
    constructor({additionalProperty}) {
        this.message = 'I come from a SpecialError class';
        this.additionalProperty = additionalProperty;
    }
}
```

making a clone of an instance of a SpecialError class instance would produce following:
```js
const {default: structuredClone} = require('@ungap/structured-clone');

const specialErrorInstance = new SpecialError({additionalProperty: 'hey'});
const clonedError = structuredClone(specialErrorInstance);

console.log(clonedError.message);  
// prints out   "I come from a SpecialError class"

console.log(clonedError.additionalProperty);  
// prints out  "undefined"
```

The behavior for cloning should ideally resemble a mix of an Error cloning and an Object cloning operation. 
A nice example of error cloning done right is done in [the @stdlib/utils/copy object cloning utility module](https://github.com/stdlib-js/stdlib/blob/bf97a9679fa31ae46f5155b2761006fd9dd1877d/lib/node_modules/%40stdlib/utils/copy/lib/deep_copy.js#L106-L148).

**Comment by WebReflection** [comment]
What would the native implementation do here? If it does what you expect happy to improve, if it doesn’t I’m not too keen in custom behaviors as out of polyfill scope.

**Comment by ohois** [comment]
I don't think that this is an error. The native implementation prints the same results

**Comment by WebReflection** [comment]
indeed ... I just tried after fixing OP code:

```js
class SpecialError extends Error {
    constructor({additionalProperty}) {
        super('I come from a SpecialError class');
        this.additionalProperty = additionalProperty;
    }
}

const specialErrorInstance = new SpecialError({additionalProperty: 'hey'});
const clonedError = structuredClone(specialErrorInstance);

console.log(clonedError.message);  
// prints out   "I come from a SpecialError class"

console.log(clonedError.additionalProperty);  
// prints out  "undefined"
```

So ... expected behavior, nothing to do here.
