### ISSUE TITLE
Unable to import stringify from "/json"

### ISSUE THREAD

**Issue by lexangle** [ungap/structured-clone#13]
This line is generating a compiler error in my Angular application:

Cannot find module '@ungap/structured-clone/json' or its corresponding type declarations.ts(2307)

`import {stringify, parse} from '@ungap/structured-clone/json';`

I can see the json.js under the esm directory under node_modules/@ungap/structured-clone. I did try to change the import to the following, but that didn't work either.

`import {stringify, parse} from '@ungap/structured-clone/esm/json';`

Any help would be much appreciated!

Thanks,
Igal

**Comment by WebReflection** [comment]
tell your compiler to ignore this module? types are provided via JSDoc here and I have zero issues with anything else using this module. If you'd like to contribute with explicit types I'd be OK, but I am afraid I don't have time to fix 3rd party issues with something that's just standard ECMAScript like this module is.
