### ISSUE TITLE
Any room for performance optimizations?

### ISSUE THREAD

**Issue by astoilkov** [ungap/structured-clone#19]
Hey, I've been wanting to use the library. However, when benchmarking against `JSON.stringify()` `structured-clone` gives me between 6-8 times slower performance.

I'm wondering, do you think there is any room for optimizing the performance?

Here's a single example of performance in our app (these are ms):
<img width="246" alt="CleanShot 2023-08-17 at 15 52 12@2x" src="https://github.com/ungap/structured-clone/assets/884810/39e955c7-8ede-4ed6-b665-d6f4e87c5997">

**Comment by WebReflection** [comment]
the structured clone algorithm does much more than just JSON so you are comparing apples to oranges *but* I can't see any obvious way to make it faster ... if you do, PR welcome!

**Comment by vipertechofficial** [comment]
https://www.npmjs.com/package/joyson
