### ISSUE TITLE
using SerializedRecord with JSON.stringify & parse does not work for data that contains `undefined`

### ISSUE THREAD

**Issue by LokiMidgard** [ungap/structured-clone#4]
I'm not sure if this behaviour is actually a problem with this lib, but from the following sentence I assume it:

> Serialized values can be safely stringified as JSON too, and deserialization resurrect all values, even recursive, or more complex than what JSON allows.

executing following code will replace undefined with null.
```ts
const x = serialize({ foo: 'test', bar: undefined, foobar: null });
const xString = JSON.stringify(x, undefined,' ');
const xObj = JSON.parse(xString);
const y = deserialize(xObj);
```

**Comment by WebReflection** [comment]
it's a 3 lines example https://github.com/ungap/structured-clone#example

```js
// as independent serializer/deserializer
import {serialize, deserialize} from '@ungap/structured-clone';

// the result can be stringified as JSON without issues
// even if there is recursive data, bigint values,
// typed arrays, and so on
const serialized = serialize({any: 'serializable'});

// the result will be a replica of the original object
const deserialized = deserialize(serialized);
```

it means you don't use JSON, you pass the serialized output to anything that can use `deserialize` to have it back.

There is [100% test coverage too](https://github.com/ungap/structured-clone/blob/main/test/index.js).

**Comment by LokiMidgard** [comment]
@WebReflection  I need to persit it on the disk and later load it again. So I need to make the object to text and back...
the serelized is an object.

Or did I missunderstood something?

**Comment by WebReflection** [comment]
@LokiMidgard ... never mind, I forgot myself how this works ... so let me write a better example!

**Comment by WebReflection** [comment]
@LokiMidgard so [this is what I was talking about](https://github.com/ungap/structured-clone#tojson) ... it's the `json` export that gives you `stringify` and `parse` that should be used *instead* of `JSON` counterparts ... I hope that helps.

In that case you have a string and you can revive it later on, as if it was JSON.

The example should be self explanatory: https://github.com/ungap/structured-clone/blob/main/esm/json.js

**Comment by WebReflection** [comment]
@LokiMidgard OK, found the issue, and I am not sure I can solve it ...

```js
console.log((
  serialize({foo: 'test', bar: undefined, foobar: null})
));
[
  [ 2, [ [Array], [Array], [Array] ] ],
  [ 0, 'foo' ],
  [ 0, 'test' ],
  [ 0, 'bar' ],
  [ 0, undefined ],
  [ 0, 'foobar' ],
  [ 0, null ]
]

console.log((
  JSON.stringify(
    serialize({foo: 'test', bar: undefined, foobar: null})
  )
));
[[2,[[1,2],[3,4],[5,6]]],[0,"foo"],[0,"test"],[0,"bar"],[0,null],[0,"foobar"],[0,null]]
```

it's JSON that is changing `undfined` into `null`, the code I wrote doesn't do anything special ... no idea why JSON would do that though, but I am not sure I can even fix that ... beside me needing to comment this or think about a possible fix, what's the big deal in serializing undefined values? 🤔

**Comment by WebReflection** [comment]
@LokiMidgard arguably, JSON does not stringify undefined neither ...

```js
JSON.stringify({foo: 'test', bar: undefined, foobar: null});

{"foo":"test","foobar":null}
```

and yet, native `structuredClone` would preserve that `bar` as undefined ... so ... what are your expectations ???

**Comment by WebReflection** [comment]
@LokiMidgard **fixed** ... apologies I had code coverage there but not for that case (actually one test had it copied and pasted with `null` ... shame on me ...) ...

Because this is a breaking change, since the output needs to be different in both serialization and revival, I had to bump the major version, but your use case is now covered.

Please let me know if that's not the case 👋

**Comment by LokiMidgard** [comment]
Thank you. It worked :)

By the way. the part with json which uses stringify and parse in this lib. I wasn't able to get it working. Maybe it was becaues I use ESModules?

The import path in the readme is `@ungap/structured-clone/json` however I need to use `@ungap/structured-clone/esm/json`.

The seccond problem was that typescript complained that the corresponding type definitions are missing. And I did not find any package that contained those.

Since I can call stringify and parse myselfe Its not a problem for me. Just thought you might be interrested. And there is a not so slight chance I just don't know how to use npm (yet)^^

**Comment by WebReflection** [comment]
> I wasn't able to get it working. Maybe it was becaues I use ESModules?

the whole project works in both ESM and CJS, but if you're using tools, you need to be sure these are updated and able to understand the [standard definition of imports](https://github.com/ungap/structured-clone/blob/main/package.json#L31-L41).

If you are pointing at files directly instead, you need to know the project folder structure, but that's unfortunate, because you shouldn't need to do so, if the env you run code is updated and aligned with the current standards.

> The seccond problem was that typescript complained that the corresponding type definitions are missing

I don't use TS but I've just updated the `/json` file with this JSDoc:

```js
/**
 * Revive a previously stringified structured clone.
 * @param {string} str previously stringified data as string.
 * @returns {any} whatever was previously stringified as clone.
 */
export const parse = str => deserialize($parse(str));

/**
 * Represent a structured clone value as string.
 * @param {any} any some clone-able value to stringify.
 * @returns {string} the value stringified.
 */
export const stringify = any => $stringify(serialize(any, options));
```

If you need anything else or you'd like to improve TS support please file a PR as I wouldn't know what to do or where to start, thanks.
