### ISSUE TITLE
Use Node.js v8 serialization API?

### ISSUE THREAD

**Issue by piranna** [ungap/structured-clone#5]
At https://nodejs.org/api/v8.html#serialization-api is it specified that Node.js `v8` module expose a `serialize()` and `deserialize()` functions that's compatible with [HTML structured clone algorythm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm), the same as this module does. Just only, maybe serialization blobs are different, can we check that, and if so, use them if available?

**Comment by WebReflection** [comment]
Here serialization is *not a blob*, it's a regular JS array that can be then stringified as JSON, and deserialization works the same, it's just a regular JS array that can recreate the original clone.

this means these kind of objects are native in the JS world, have nothing to do with Node.js specific *Buffer*, and on top of that, the serialization/deserialization is an extra, not really what this polyfill is about.

This polyfill is about providing *structuredClone* utility as close as possible to the native one, with inevitable limitations the browser has. *structuredClone* itself has no intermediate format, it's just a convenient convention I've re-adapted from [flatted](https://www.npmjs.com/package/flatted).

As summary: if you use Node.js 0.8 or higher, you never cared about this polyfill, but if you are on the browser, you likely don't want the Node.js implementation, as it doesn't work, or integrate, as well as the current underlying implementation detail.

What you are looking for, is a browser oriented polyfill for Node.js v8 implementation of *serialize* or *deserialize*, and that's not what this polyfill is about.

I hope this reasons well.

**Comment by piranna** [comment]
Make sense. My question was more about in case the Node.js native implementation could be used in case they are available, the same as the `structuredClone()` function, but seems like underlying serialized formats are not compatible, and trying to do so would preveng interoperatibility, isn't it?

**Comment by WebReflection** [comment]
> underlying serialized formats are not compatible, and trying to do so would preveng interoperatibility, isn't it?

for *structuredClone* nobody should care about underlying implementation (but I agree as Node.js polyfill this might be a limitation because of the missing ability from the browser world) but for browsers, the intermediate format also works natively in IndexedDB and it has no Buffer representation in browsers, hence no benefits in having one, just a slowdown for browsers.

Last, but not least, it's impossible to synchronously feature detect and import those utilities so that having Node.js modules here would break not only browsers but also Deno land.

Again, if you want Node.js serialize/deserialize, use that or look for a browser polyfill that does that.

It won't happen here.

**Comment by piranna** [comment]
> for _structuredClone_ nobody should care about underlying implementation

Yes, at the end, you only want a copy, not how it was get.


> it has no Buffer representation in browsers

Node.js Buffers are sugar syntax on top of ArrayBuffers, so it could be feasable... :-)


> Again, if you want Node.js serialize/deserialize, use that or look for a browser polyfill that does that.

Honestly, I'm included the serialized info in a JSON (I'm just only serializing the fields that I know *could* have non JSON compatible data), so probably the binary format would not work for me at all, just only maybe an implementation compatible with Node.js ones could be useful to somebody, that's why I asked about if the internal formats are compatible or could be adapted :-)

**Comment by WebReflection** [comment]
I have no idea because I haven't tested, used, or checked, *ever*, the Node.js implementation, and I am not planning to do anything in here because it doesn't solve any issue I have and it's not useful for the *browser* *structuredClone* polyfill.

Have a nice Sunday 👋

**Comment by piranna** [comment]
Yeah, no issues :-) Have a nice Sunday you too :-D
