### ISSUE TITLE
CDN hosted or copy/paste version

### ISSUE THREAD

**Issue by simonferndriger** [ungap/structured-clone#6]
Hi

Thank you for your polyfill, however, it requires an import and build step. I don't mind the import, but since I don't do builds I was hoping to get an already built version to easily copy/paste in my simple project.

Thanks
Simon

**Comment by WebReflection** [comment]
there are no dependencies and if you don't mind the import, why don't you just import it?

  * [skypack](https://www.skypack.dev/view/@ungap/structured-clone)
  * [unpkg](https://unpkg.com/@ungap/structured-clone@1.0.1/esm/index.js)
  * every other CDN that delivers *npm* packages

**Comment by simonferndriger** [comment]
Hi

Thank you for pointing that out, sorry, did not see this easy way of importing it. So is this correct when I do the follwing? Because I only want to import it if necessary. What would I have to do if I wanted to host it myself?

`if(typeof structuredClone !== 'function') (async () => { const structuredClone = await import('https://cdn.skypack.dev/@ungap/structured-clone'); })();`

**Comment by WebReflection** [comment]
```js
const {structuredClone = (await import('https://cdn.skypack.dev/@ungap/structured-clone')).default} = self;
```

**Comment by simonferndriger** [comment]
Thank you 🙏 Now it seems to work with the following:

`    (async () => {
        const { structuredClone = (await import('https://cdn.skypack.dev/@ungap/structured-clone')).default } = self;
    })();`
