### ISSUE TITLE
support for cloning typed arrays / arraybuffer

### ISSUE THREAD

**Issue by jimmywarting** [ungap/structured-clone#7]
First i just want to say thank you for a such a awesome library, thinking of using this even for my client <-> server API
it not only looked like some repetitive data also got smaller in size (cuz it reuse same key/value if it already exist in the flat array)
But it also keep things such as Date as an actual date object

I just played around with it and it would also be cool if we could get in binary data there as well and this would become a solid replacement for something like bson / ejson but with a smaller footprint and without the need of any built in nodejs core modules

```js
import('https://cdn.jsdelivr.net/npm/@ungap/structured-clone@1.0.1/esm/json.min.js').then(x => {
  const foo = new Uint8Array(1024)
  const bar = new Uint8Array(foo.buffer, 0, 512)
  const baz = new Uint8Array(foo.buffer, 512)
  
  console.log(bar)
  console.log(baz)

  const clone = x.parse(x.stringify({bar, baz}))
  console.log(clone.bar.buffer === clone.baz.buffer)
  
  const clone2 = structuredClone({bar, baz})
  console.log(clone2.bar.buffer === clone2.baz.buffer)
})
```
I think that we need to keep a record of all the underlying ArrayBuffers at one single place as a "source of truth"
cuz a typed arrays is just a references to some other ArrayBuffers with a byteOffset & byteLength... that's all it really is. 
Two uint8array can use the same ArrayBuffer but with a different size and a offset. 

if something is a ArrayBufferView then:
1. You should store the ArrayBuffer somewhere in uniq array, (call it blobStore) 
2. if the arraybuffer have already been added then it should use same existent index as a key
3. then typed arrays should just be serilized to something like `[['Uint8Array', arraybuffer, offset, size]]`<br>Not as in `[["Uint8Array",[0,0,0,0,0]]]`
4. then right before you stringify the hole blobStore then i think that you should convert the hole ArrayBuffer to a base64 string to save space

5. then for the deserialize you should convert all text in `blobStore` back into arrayBuffers
6. then the typed array should only references the stuff that exist in the `blobStore`

**Comment by WebReflection** [comment]
PR welcome 👍

**Comment by jimmywarting** [comment]
> PR welcome 👍

I just might do that when I am back home and have some free time.
Bit confused of how the code actually works. Might take a bit of to find a solution that works

**Comment by WebReflection** [comment]
[Here is where you want to implement a smarter Array serialization](https://github.com/ungap/structured-clone/blob/main/esm/serialize.js#L80-L82) ... those are typed Array spread and never reused.

You probably need to find an index instead to use for the underlying buffer but indeed this is not super simple neither straight forward, although it's possible.

**Comment by jimmywarting** [comment]
> [Here is where you want to implement a smarter Array serialization](https://github.com/ungap/structured-clone/blob/main/esm/serialize.js#L80-L82) ... those are typed Array spread and never reused.

I came to that conlution after trying you code out a bit 👍 

> You probably need to find an index instead to use for the underlying buffer but indeed this is not super simple neither straight forward, although it's possible.

Wasn't easy or straight forward as you said but i manage to re-use your Map/Array index store hopefully did something that works well, i did manage to use same index for the ArrayBuffer.

**Comment by WebReflection** [comment]
closing, as apparently there's no progress nor interest in this.
