### ISSUE TITLE
support for file/blobs

### ISSUE THREAD

**Issue by jimmywarting** [ungap/structured-clone#9]
Blob's are a bit tricky, they can only be read lazily. But i happen to know a trick of how to read them synchronous. it's a bit tricky and might not always work for each and every env/context

```js
const blob = new Blob(['123'])
const xhr = new XMLHttpRequest()
const url = URL.createObjectURL(blob)

// required if you need to read binary data (you can't use responseType while using sync xhr)
xhr.overrideMimeType('text/plain; charset=x-user-defined') 
xhr.open('GET', url, false)
xhr.send()

const uint8 = Uint8Array.from(xhr.response, c => c.charCodeAt(0))
const text = new TextDecoder().decode(uint8)
const arrayBuffer = uint8.buffer
const json = JSON.parse(text)
```

if you are using workers then it might be possible to spin up a new worker and use [Atomics](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics) wizard to pause/resume

---

just some idea that i got...
if you need to create a file list: then there is a roundabout way of creating a list using something like:
```js
function FileListItems (files) {
  var b = new ClipboardEvent("").clipboardData || new DataTransfer()
  for (var i = 0, len = files.length; i<len; i++) b.items.add(files[i])
  return b.files
}

var fileList = FileListItems([
  new File(['content'], 'sample1.txt'),
  new File(['abc'], 'sample2.txt')
])
```

**Comment by WebReflection** [comment]
>  it's a bit tricky and might not always work for each and every env/context

I prefer not having these at all than having these "*sometimes broken*" + this module is *not* for browsers only, it works pretty well in Node.js too and that's desired when it comes to its JSON helpers for client/server exchanges.

I don't think I want to work on this.

**Comment by jimmywarting** [comment]
That's alright if it dosen't.
All doe it's also possible turn something async into something sync in NodeJS using atomics 
found this post just the other day: https://giuseppegurgone.com/synchronizing-async-functions
Trying to do something similar in Browser is more tricker cuz you would need `sharedArrayBuffer` and enabling those requires you to respond with extra response [headers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements) in order to use it...

fyi, all enviorment now has Blob built in, so expect it will be more used later
